spring:
    application:
        name: manager-app
    datasource:
        url: jdbc:postgresql://localhost:5433/service
        username: user
        password: password
    jpa:
        show-sql: true

server:
    port: 8080

service:
    catalog:
        uri: http://localhost:8081
        username: user
        password: password